#!/bin/sh
# Generates docker-compose.override.yml from PHOTO_LIBRARIES in .env so
# multi-drive users can have several photo paths visible to fineshyt
# without hand-editing YAML.
#
# Behavior:
#   PHOTO_LIBRARIES unset/empty  → remove generated override (single-drive mode)
#   PHOTO_LIBRARIES set          → generate override mounting each drive at
#                                  the same path inside the container
#                                  (path-mirroring), so users type real
#                                  paths in the gallery
#
# Path-mirroring means the bind-mount target equals the bind-mount source:
# host  /Volumes/Wedding-2024  →  container  /Volumes/Wedding-2024
# That way the chip system in the LiveView can show those exact paths
# and clicking a chip just works.

set -eu

ENV_FILE="${ENV_FILE:-.env}"
OVERRIDE_FILE="${OVERRIDE_FILE:-docker-compose.override.yml}"
GENERATED_HEADER="# generated by scripts/generate-compose-override.sh — do not edit by hand"

if [ ! -f "$ENV_FILE" ]; then
  exit 0
fi

PHOTO_LIBRARIES_VALUE=$(grep -E '^PHOTO_LIBRARIES=' "$ENV_FILE" | head -1 | cut -d= -f2- || true)
# We also need PHOTO_LIBRARY: the base compose.yml already path-mirrors it,
# so we must NOT also emit a mount for it in the override (Docker errors
# out with `mount source path ... file exists` on duplicate bind-mounts
# to overlapping host_mnt subtrees).
PHOTO_LIBRARY_VALUE=$(grep -E '^PHOTO_LIBRARY=' "$ENV_FILE" | head -1 | cut -d= -f2- || true)

# Empty or unset → remove our generated file (but never delete a file the
# user wrote by hand).
if [ -z "$PHOTO_LIBRARIES_VALUE" ]; then
  if [ -f "$OVERRIDE_FILE" ] && head -1 "$OVERRIDE_FILE" | grep -q "generate-compose-override"; then
    rm "$OVERRIDE_FILE"
    echo "→ removed stale $OVERRIDE_FILE (PHOTO_LIBRARIES is empty)"
  fi
  exit 0
fi

# Warn about missing paths (typo'd, drive unplugged) but DON'T hard-fail.
# Originally we exited 1 here because compose mode would mount every path
# and a missing one produced an empty bind-mount. Since C4 the desktop
# path doesn't use compose at all — a missing drive there means "you
# can't ingest from it right now" (gallery handles it gracefully at
# ingest time), not "the app can't boot". For compose mode we just skip
# the missing paths from the override, which is the same outcome as if
# the user hadn't listed them.
MISSING=""
OLD_IFS="$IFS"
IFS=:
for path in $PHOTO_LIBRARIES_VALUE; do
  [ -z "$path" ] && continue
  if [ ! -d "$path" ]; then
    MISSING="$MISSING\n  - $path"
  fi
done
IFS="$OLD_IFS"

if [ -n "$MISSING" ]; then
  printf "⚠ PHOTO_LIBRARIES contains paths not present right now (drive unplugged?):%b\n" "$MISSING"
  echo "  skipping them from the compose override; desktop mode ignores this list anyway."
fi

# Write the override file. Only the orchestrator service needs these
# mounts: in full `compose` mode it runs containerized and reads source
# files off disk to stream them to the ai_worker. The ai_worker itself is
# filesystem-independent (it receives source bytes as multipart uploads),
# so it gets no photo-library mounts — emitting them would just risk the
# `mkdir /host_mnt/...: file exists` collisions seen with exFAT drives.
#
# Skip any path that equals PHOTO_LIBRARY — the base compose.yml already
# emits a path-mirrored bind-mount for it on the orchestrator, and Docker
# rejects the resulting duplicate mount with `mkdir /host_mnt/...: file exists`.
{
  echo "$GENERATED_HEADER"
  echo "# regenerated automatically by 'make compose-init' whenever"
  echo "# PHOTO_LIBRARIES changes in .env."
  echo "services:"
  echo "  orchestrator:"
  echo "    volumes:"
  IFS=:
  for path in $PHOTO_LIBRARIES_VALUE; do
    [ -z "$path" ] && continue
    [ "$path" = "$PHOTO_LIBRARY_VALUE" ] && continue
    # Skip paths that don't exist on the host — Docker would reject the
    # bind-mount otherwise. Already warned above. Desktop mode doesn't
    # use this file at all, so this only matters for `make compose`.
    [ ! -d "$path" ] && continue
    echo "      - $path:$path:ro"
  done
  IFS="$OLD_IFS"
} > "$OVERRIDE_FILE"

DRIVE_COUNT=$(echo "$PHOTO_LIBRARIES_VALUE" | tr ':' '\n' | grep -c . || true)
SKIPPED_NOTE=""
if echo "$PHOTO_LIBRARIES_VALUE" | tr ':' '\n' | grep -qxF "$PHOTO_LIBRARY_VALUE" 2>/dev/null; then
  SKIPPED_NOTE=" (skipped PHOTO_LIBRARY entry; base compose mounts it)"
fi
echo "→ wrote $OVERRIDE_FILE with $DRIVE_COUNT drive(s)$SKIPPED_NOTE"
