#!/bin/sh
# Generates docker-compose.override.yml from PHOTO_LIBRARIES in .env so
# multi-drive users can have several photo paths visible to fineshyt
# without hand-editing YAML.
#
# Behavior:
#   PHOTO_LIBRARIES unset/empty  → remove generated override (single-drive mode)
#   PHOTO_LIBRARIES set          → generate override mounting each drive at
#                                  the same path inside the container
#                                  (path-mirroring), so users type real
#                                  paths in the gallery
#
# Path-mirroring means the bind-mount target equals the bind-mount source:
# host  /Volumes/Wedding-2024  →  container  /Volumes/Wedding-2024
# That way the chip system in the LiveView can show those exact paths
# and clicking a chip just works.

set -eu

ENV_FILE="${ENV_FILE:-.env}"
OVERRIDE_FILE="${OVERRIDE_FILE:-docker-compose.override.yml}"
GENERATED_HEADER="# generated by scripts/generate-compose-override.sh — do not edit by hand"

if [ ! -f "$ENV_FILE" ]; then
  exit 0
fi

PHOTO_LIBRARIES_VALUE=$(grep -E '^PHOTO_LIBRARIES=' "$ENV_FILE" | head -1 | cut -d= -f2- || true)

# Empty or unset → remove our generated file (but never delete a file the
# user wrote by hand).
if [ -z "$PHOTO_LIBRARIES_VALUE" ]; then
  if [ -f "$OVERRIDE_FILE" ] && head -1 "$OVERRIDE_FILE" | grep -q "generate-compose-override"; then
    rm "$OVERRIDE_FILE"
    echo "→ removed stale $OVERRIDE_FILE (PHOTO_LIBRARIES is empty)"
  fi
  exit 0
fi

# Validate every path exists on the host before we write the file. A
# typo'd drive path silently produces an empty mount and confuses the
# user, so fail loudly here.
MISSING=""
OLD_IFS="$IFS"
IFS=:
for path in $PHOTO_LIBRARIES_VALUE; do
  [ -z "$path" ] && continue
  if [ ! -d "$path" ]; then
    MISSING="$MISSING\n  - $path"
  fi
done
IFS="$OLD_IFS"

if [ -n "$MISSING" ]; then
  printf "✗ PHOTO_LIBRARIES contains paths that don't exist on this machine:%b\n" "$MISSING"
  echo "  fix .env (typo? drive not mounted?) and re-run."
  exit 1
fi

# Write the override file. Both services need the same set of mounts since
# they share file paths via the database.
{
  echo "$GENERATED_HEADER"
  echo "# regenerated automatically by 'make compose-init' whenever"
  echo "# PHOTO_LIBRARIES changes in .env."
  echo "services:"
  echo "  orchestrator:"
  echo "    volumes:"
  IFS=:
  for path in $PHOTO_LIBRARIES_VALUE; do
    [ -z "$path" ] && continue
    echo "      - $path:$path:ro"
  done
  echo "  ai_worker:"
  echo "    volumes:"
  for path in $PHOTO_LIBRARIES_VALUE; do
    [ -z "$path" ] && continue
    echo "      - $path:$path:ro"
  done
  IFS="$OLD_IFS"
} > "$OVERRIDE_FILE"

DRIVE_COUNT=$(echo "$PHOTO_LIBRARIES_VALUE" | tr ':' '\n' | grep -c . || true)
echo "→ wrote $OVERRIDE_FILE with $DRIVE_COUNT drive(s)"
